ZSH_THEME="henanigans"
export ZSH="/home/ubuntu/.oh-my-zsh"
fpath=(~/.oh-my-zsh/custom/completions $fpath)
DISABLE_UPDATE_PROMPT=true
plugins=(
    aws
    command-not-found
    common-aliases
    git
    npm
    pip
    python
    sudo
    fast-syntax-highlighting
    zsh-autosuggestions
    zsh-history-enquirer
)
source $ZSH/oh-my-zsh.sh
echo 'will cite' | parallel --citation >> /dev/null 2>&1
alias l='ls -hl'
alias ll='ls -hlA'
alias tree='tree -Ca'
git config --global --add safe.directory /home/ubuntu/lunchbox
source /home/ubuntu/lunchbox/docker/scripts/x-tools.sh
x_env_activate_dev;
