services:
  lunchbox:
    container_name: lunchbox
    image: lunchbox:dev
    platform: linux/amd64
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "4000:9000"
      - "4080:8080"
    userns_mode: "host"
    user: ubuntu
    env_file:
      - config/dev-env
    volumes:
      - ../:/home/ubuntu/lunchbox
      - ~/.ssh:/home/ubuntu/.ssh:ro
      - ./config/jupyter:/home/ubuntu/.jupyter
      - ./config/zshrc:/home/ubuntu/.zshrc
    working_dir: "/home/ubuntu"
