version: "3.8"
services:
  lunchbox:
    container_name: lunchbox
    image: lunchbox
    build:
      context: .
      dockerfile: lunchbox.dockerfile
    ports:
      - "4000:9000"
    userns_mode: "host"
    user: root
    volumes:
      - ../:/root/lunchbox
      - ~/.ssh:/root/.ssh
      - ./jupyter:/root/.jupyter
    working_dir: "/root/lunchbox/python"
    command: "tail -f /dev/null"
