# Run the lunchbox service stack

# Required variables
#  - CURRENT_USER: The uid:gid value to ensure the bind mounted volume's
#                  permissions match the host

version: "3.8"
services:
  lunchbox:
    container_name: lunchbox
    image: lunchbox
    build:
      context: .
      dockerfile: lunchbox.dockerfile
    ports:
      - "9013:9000"
    userns_mode: "host"
    user: root
    volumes:
      - ../:/root/lunchbox
      - ./jupyter:/root/.jupyter
    working_dir: "/root/lunchbox/python"
    command: "tail -f /dev/null"
