version: "3.8"
services:
  lunchbox:
    container_name: lunchbox
    image: lunchbox
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "4000:9000"
    userns_mode: "host"
    user: ubuntu
    volumes:
      - ../:/home/ubuntu/lunchbox
      - ~/.ssh:/home/ubuntu/.ssh:ro
      - ./jupyter:/home/ubuntu/.jupyter
      - ./zshrc:/home/ubuntu/.zshrc
      - ./dev/pyproject.toml:/home/ubuntu/dev/pyproject.toml
      - ./dev/pdm.toml:/home/ubuntu/dev/.pdm.toml
      - ./dev/pdm.lock:/home/ubuntu/dev/pdm.lock
      - ./prod/pyproject.toml:/home/ubuntu/prod/pyproject.toml
      - ./prod/pdm.toml:/home/ubuntu/prod/.pdm.toml
      - ./prod/pdm.lock:/home/ubuntu/prod/pdm.lock
    working_dir: "/home/ubuntu"
    command: "tail -f /dev/null"
