version: "3.8"
services:
  lunchbox:
    container_name: lunchbox
    image: lunchbox
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "4000:9000"
    userns_mode: "host"
    user: ubuntu
    volumes:
      - ../:/home/ubuntu/lunchbox
      - ~/.ssh:/home/ubuntu/.ssh
      - ./jupyter:/home/ubuntu/.jupyter
      - ./ipython:/home/ubuntu/.ipython
    working_dir: "/home/ubuntu"
    command: "tail -f /dev/null"
