name: Feature

on:
  push:
    branches: [ github-workflows ]

env:
  repo: "${{ github.event.repository.name }}"
  cli: "bin/${{ github.event.repository.name }}"
  org: "thenewflesh"
  org_url: "github.com"
  docker_registry: "docker.io"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.docker_registry }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Pull image
        run: $($cli docker-pull-dev) || echo "docker image not found"

      - name: Build image
        run: $cli docker-build-from-cache

      - name: Start container
        run: $cli docker-start

  docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Docs
        run: $cli docs

      - name: Metrics
        run: $cli docs-metrics

      - name: Architecture
        run: $cli docs-architecture

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Lint
        run: $cli test-lint

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: $cli test-coverage
