name: Feature

on:
  push:
    branches: [ github-workflows ]

env:
  repo: ${{ github.event.repository.name }}
  cli: "bin/${{ github.event.repository.name }}"
  org: "{{ cc.git_organization }}"
  org_url: "{{ cc.organization_url }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

    #   - name: Build Image
    #     uses: hoverkraft-tech/compose-action@v2.0.1
    #     with:
    #       compose-file: "./docker/docker-compose.yml"

      - name: Build Image
        run: |
            env

      - name: pwd
        run: |
            pwd
